team6/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/profile_id', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('mypage/<int:profile_id>', views.mypage, name="mypage"),
]

team6/team6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cigarettes.urls')),
    path('accounts/', include('accounts.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



team6/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=30)
    email = models.TextField()
    is_admin = models.BooleanField(default=False)
    
    def __str__(self):
        return self.user.username

team6/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from .models import Profile

def signup(request):
    auth_mode = 'signup'    
    if request.method == 'POST':
        if request.POST.get('password1') == request.POST.get('password1'):
            user = User.objects.create_user(request.POST.get('username'), password=request.POST.get('password1'))

            profile = Profile()
            profile.nickname = request.POST.get('nickname')
            profile.email = request.POST.get('email')
            profile.user = user
            profile.save()

            auth.login(request, user)
            return redirect('cigarettes:index')
    return render(request, 'accounts/auth_form.html', {'auth_mode': auth_mode})

    
def login(request):
    auth_mode = 'login'
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('cigarettes:index')
        else :
            return render(request, 'accounts/auth_form.html', {'error' : 'username or password is incorrect!'})
    return render(request, 'accounts/auth_form.html', {'auth_mode': auth_mode})

def logout(request):
    # if request.method == 'POST':
    auth.logout(request)
    return redirect('cigarettes:index')
    # return render(request, 'accounts/signup.html')

def mypage(request, profile_id):
    profile = Profile.objects.get(id = profile_id)
    context = {'profile' : profile}
    return render(request, 'accounts/mypage.html', context)

team6/accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% block content %}
<style>
h1 {
    margin-top: 30px;
    text-align: center;
    font-size: 1.75rem;
    font-family: 'Jua', sans-serif;
}

p {
    font-family: 'Do Hyeon', sans-serif;
}

form {
    justify-content: center;
    font-family: 'Do Hyeon', sans-serif;
}

input {
    width: 100%;
}

.signup, .login {
    width: 100%;
    padding: .8em 0 10px .8em;
    background-color: #28A55F;
    border: none;
    color:  white;
    cursor: pointer;
    text-transform: uppercase;
    margin-top: 20px;
}

</style>

{% ifequal auth_mode 'signup' %}

        <h1>Sign up</h1>
        <hr>
        <p>담배를 좋아하는 여러분,<br>
            만나서 반갑습니다.<br>
            CigaReco의 회원이 되어주세요!</p>
        <form method="POST" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            Username : 
            <br>
            <input type="text" name="username" value="">
            <br>
            Password:
            <br>
            <input type="password" name="password1" value="">
            <br>
            Confirm Password:
            <br>
            <input type="password" name="password2" value="">
            <hr>
            Nickname:
            <br>
            <input type="text" name="nickname" value="">
            <br>
            E-mail:
            <br>
            <input type="text" name="email" value="">
            <br>
            <br>
            <input class="signup" type="submit" value="Signup">
        </form>

    {% else %}

        <h1>Login</h1>
        <hr>
        <p>더 많은 서비스를 이용하시려면<br>
             로그인 해주세요!</p>
        <form method="POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            Username : 
            <br>
            <input type="text" name="username" value="">
            <br>
            Password:
            <br>
            <input type="password" name="password" value="">
            <br>
            <br>
            <input class="login" type="submit" value="Login">
        </form>

    {% endifequal %}

{% endblock %}

team6/accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    h1 {
            margin-top: 30px;
            text-align: center;
            font-size: 1.75rem;
            font-family: 'Jua', sans-serif;
        }

    p, h2 {
        font-family: 'Do Hyeon', sans-serif;
    }


</style>
<h1>My Page</h1>
<hr>
<p>{{ user.username }}님의 회원 정보</p>
<p>E-mail : {{ user.profile.email }}</p>
<p>Nickname : {{ user.profile.nickname }}</p>
<hr>
<h2>내가 좋아한 담배 보기</h2>
{% endblock %}