team6/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/profile_id', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('mypage/<int:profile_id>', views.mypage, name="mypage"),
]

team6/cigarettes/urls.py
from django.urls import path
from . import views

app_name = 'cigarettes'

urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<int:cigarette_id>/',views.detail, name="detail"),
    path('like/<int:cigarrte_id>/',views.like, name="like"),
    path('detail/<int:cigarette_id>/comment', views.comment, name="comment"),
    path('newCigarette/', views.new_cigarette, name="new_cigarette"),
    path('newElecCigarette/', views.new_elec_cigarette, name="new_elec_cigarette"),
    path('createCigarette/', views.create_cigarette, name="create_cigarette"),
    path('createElecCigarette/', views.create_elec_cigarette, name="create_elec_cigarette"),
    path('editCigarette/<int:edit_cigarette_id>', views.edit_cigarette, name="edit_cigarette"),
    path('editElecCigarette/<int:edit_elec_cigarette_id>', views.edit_elec_cigarette, name="edit_elec_cigarette"),
    path('updateCigarette/<int:update_cigarette_id>', views.update_cigarette, name="update_cigarette"),
    path('updateElecCigarette/<int:update_elec_cigarette_id>', views.update_elec_cigarette, name="update_elec_cigarette"),
]

team6/team6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cigarettes.urls')),
    path('accounts/', include('accounts.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



team6/cigarettes/models.py
import os
from django.conf import settings
from django.db import models
from django.utils import timezone
from accounts.models import Profile
from polymorphic.models import PolymorphicModel
from easy_thumbnails.fields import ThumbnailerImageField

# Create your models here.

class Tobacco(PolymorphicModel):
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='img', blank=True, null=True)
    thumbnail = ThumbnailerImageField(upload_to='media/cigarette', blank=True)
    price = models.CharField(max_length=10)
    rel_date = models.CharField(max_length=20, blank=True)
    nicotine =  models.FloatField()
    TAR = models.FloatField()
    feel_of_hit = models.CharField(max_length=10, default='데이터 없음')
    score = models.FloatField(default=0)
    total_like = models.PositiveIntegerField(default=0)
    like_user = models.ManyToManyField(Profile)

    def delete(self, *args, **kargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.photo.path))
        super(Tobacco, self).delete(*args, **kargs)

    def __str__(self):
        return self.brand+self.name

    class Meta:
        ordering = ['-rel_date']

class Cigarettes(Tobacco):
    is_local = models.BooleanField()
    is_menthol = models.BooleanField()

class ElecCigarettes(Tobacco):
    c_type = models.CharField(max_length=20)

class Comment(models.Model):
    belongs_to_user = models.ForeignKey(Profile, on_delete=models.CASCADE, null = True)
    belongs_to_tobacco = models.ForeignKey(Tobacco, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    feel_of_hit = models.CharField(max_length=10)
    score = models.PositiveIntegerField(default=3)
    content = models.TextField()

class Request(models.Model):
    is_elec = models.BooleanField()
    is_added = models.BooleanField(default=False)
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    price = models.CharField(max_length=10)
    rel_date = models.CharField(max_length=20, blank=True)
    nicotine =  models.FloatField(blank=True)
    TAR = models.FloatField(blank=True)

team6/cigarettes/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from cigarettes.models import Tobacco, Cigarettes, ElecCigarettes, Comment 
from accounts.models import Profile
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    if request.user.is_anonymous:
        tobacco = Tobacco.objects.all()
        context = {'tobacco':tobacco}
        return render(request, 'cigarettes/index.html', context)    
    else:
        tobacco = Tobacco.objects.all()
        user = request.user
        profile = Profile.objects.get(user = user)
        context = {'tobacco':tobacco, 'profile':profile}
        # if Profile.objects.filter(user = user) is None:
            

        # context = {'tobacco':tobacco}
        return render(request, 'cigarettes/index.html', context)

def detail(request, cigarette_id):
    tobacco = get_object_or_404(Tobacco, pk = cigarette_id)
    comment_list = Comment.objects.filter(belongs_to_tobacco=tobacco)

    foh_dict = {'상':0,'중':0,'하':0}
    score = 0

    if not len(comment_list) == 0:
        for comment in comment_list:
            score += comment.score 
            if comment.feel_of_hit == '상':
                foh_dict['상'] += 1
            elif comment.feel_of_hit == '중':
                foh_dict['중'] += 1
            else:
                foh_dict['하'] += 1
        
        tobacco.score = score / len(comment_list)

        if (foh_dict['상'] > foh_dict['중']) and (foh_dict['상'] > foh_dict['하']):
            tobacco.feel_of_hit = '상'
        elif (foh_dict['하'] > foh_dict['중']) and (foh_dict['하'] > foh_dict['상']):
            tobacco.feel_of_hit = '하'
        else: tobacco.feel_of_hit = '중'

    tobacco.save()

    context = {
        'tobacco':tobacco,
        'comment_list':comment_list,
    }
    
    return render(request,"cigarettes/cigarette_detail.html", context)

def like(request, cigarette_id):

    tobacco = Tobacco.objects.get(id=cigarette_id)
    try:
        user = request.user
        profile = Profile.objects.get(user=user)
    except: # 유저로그인 안했을경우
        return redirect('accounts:login')

    check_like = tobacco.filter(like_user=profile)

    if check_like.exists():
        tobacco.like_user.remove(profile)
        tobacco.total_like -= 1
        tobacco.save()

    else:
        tobacco.like_user.add(profile)
        tobacco.total_like += 1
        tobacco.save()

    return redirect('cigarettes:detail', cigarette_id)

def comment(request, cigarette_id):

    if request.method == "POST":
        comment = Comment()
        comment.belongs_to_tobacco = Tobacco.objects.get(id=cigarette_id)
        try:
            user = request.user
            profile = Profile.objects.get(user=user)
            comment.belongs_to_user = profile
            comment.feel_of_hit = request.POST['feel_of_hit']
            comment.score = request.POST['score']
            comment.content = request.POST['content']
            comment.save()
        except: #유저 로그인 안했을 경우
            return redirect('accounts:login')
        return redirect('cigarettes:detail', cigarette_id)
    else:
        try:
            user = request.user
            profile = Profile.objects.get(user=user)
            context = {'profile': profile, 'cigarette_id':cigarette_id}
        except: #유저 로그인 안했을 경우
            return redirect('accounts:login')
        return render(request, 'cigarettes/comment.html', context)
    return redirect('tobacco:detail', cigarette_id)

def new_cigarette(request):
    mode = "create"
    tobacco_type = "cigarette"
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context = {'tobacco_type' : tobacco_type, 'mode' : mode, 'profile':profile}
    return render(request, 'cigarettes/create_tobacco.html', context)

def new_elec_cigarette(request):
    mode = "create"
    tobacco_type = "elec_cigarette"
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context = {'tobacco_type' : tobacco_type, 'mode' : mode, 'profile':profile}
    return render(request, 'cigarettes/create_tobacco.html', context)

def create_cigarette(request):
    
    cigarette = Cigarettes()
    cigarette.is_local = request.POST.get('is_local')
    cigarette.brand = request.POST.get('brand')
    cigarette.name = request.POST.get('name')
    cigarette.photo = request.FILES.get('photo')
    cigarette.price = request.POST.get('price')
    cigarette.TAR = request.POST.get('tar')
    cigarette.nicotine = request.POST.get('nicotine')
    cigarette.rel_date = request.POST.get('rel_date')
    cigarette.is_menthol = request.POST.get('is_menthol')
    cigarette.save()

    #return redirect('//' +str(new_post.id))
    return redirect('cigarettes:index')

def create_elec_cigarette(request):
    elec_cigarette = ElecCigarettes()
    elec_cigarette.c_type = request.POST.get('c_type')
    elec_cigarette.brand = request.POST.get('brand')
    elec_cigarette.name = request.POST.get('name')
    elec_cigarette.photo = request.FILES.get('photo')
    elec_cigarette.price = request.POST.get('price')
    elec_cigarette.TAR = request.POST.get('tar')
    elec_cigarette.nicotine = request.POST.get('nicotine')
    elec_cigarette.rel_date = request.POST.get('rel_date')
    
    elec_cigarette.save()

    #return redirect('//' +str(new_post.id))
    return redirect('cigarettes:index')

def edit_cigarette(request, edit_cigarette_id):
    mode = "update"
    tobacco_type = "cigarette"
    edit_cigarette = get_object_or_404(Tobacco, pk=edit_cigarette_id)
    context = {'tobacco_type' : tobacco_type, 'edit_cigarette' : edit_cigarette, 'mode' : mode}

    return render(request, 'cigarettes/create_tobacco.html', context)


def update_cigarette(request, update_cigarette_id):
    cigarette = get_object_or_404(Tobacco, pk=update_cigarette_id)
    cigarette.is_local = request.POST.get('is_local')
    cigarette.brand = request.POST.get('brand')
    cigarette.name = request.POST.get('name')
    cigarette.price = request.POST.get('price')
    cigarette.TAR = request.POST.get('tar')
    cigarette.nicotine = request.POST.get('nicotine')
    cigarette.rel_date = request.POST.get('rel_date')
    cigarette.is_menthol = request.POST.get('is_menthol')
    cigarette.save()

    return redirect('/detail/'+ str(update_cigarette_id)+'/')


def edit_elec_cigarette(request, edit_elec_cigarette_id):
    mode = "update"
    tobacco_type = "elec_cigarette"
    edit_cigarette = get_object_or_404(Tobacco, pk=edit_elec_cigarette_id)
    context = {'tobacco_type' : tobacco_type, 'edit_elec_cigarette' : edit_elec_cigarette, 'mode' : mode}

    return render(request, 'cigarettes/create_tobacco.html', context)


def update_elec_cigarette(request, update_elec_cigarette_id):
    elec_cigarette = get_object_or_404(Tobacco, pk=update_elec_cigarette_id)
    elec_cigarette.c_type = request.POST.get('c_type')
    elec_cigarette.brand = request.POST.get('brand')
    elec_cigarette.name = request.POST.get('name')
    elec_cigarette.price = request.POST.get('price')
    elec_cigarette.TAR = request.POST.get('tar')
    elec_cigarette.nicotine = request.POST.get('nicotine')
    elec_cigarette.rel_date = request.POST.get('rel_date')
    elec_cigarette.save()

    return redirect('/detail/'+ str(update_cigarette_id)+'/')

team6/cigarettes/templates/cigarettes/_nav.html
<!-- css -->
<style>
nav {
    background-color: orange;
    font-family: 'Jua', sans-serif;
    color: white;
    font-size: 1.75rem;
    justify-content: center;
    display: flex;
    align-items: center;
    height: 65px;
    width: 100%;
}

#toggle{
  display:none;
  margin:0;
  padding:0;
}
label{
  font-size:28px;
  position:fixed;
  left:20px;
  top:8px;
  transition:0.5s;
  cursor:pointer;
}

ul {
  list-style:none;
  background:#333;
  width:150px;
  padding-top:30px;
  position:fixed;
  height:100%;
  left:-180px;
  transition:0.5s;
}
li {
  font-family: 'Jua', sans-serif;
  color:#007BFF;
  margin:20px;
  text-transform:capitalize;
  text-align:right;
  cursor:pointer;
}

li:hover{
  
}

li a:hover {
    color:#fff;
    text-decoration: none;
    transition:0.5s;
}
#toggle:checked + div ul{
  left:0;
}
#toggle:checked + div label{
  left:20px;
}
label:hover{
  color: #fff;
}

</style>

<!-- html -->
<nav>
    <h3>CigaReco</h3>
</nav>
<input type="checkbox" id="toggle">
<div>
  <label for="toggle">&#9776;</label>
  <ul>
    <li><a href="{% url 'cigarettes:index' %}">cigarettes</a></li>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <li><a href="{% url 'accounts:logout' %}">logout</a></li> 
        {% else %}
          <li><a href="{% url 'accounts:logout' %}">logout</a></li> 
          {% comment %} <li><a href="{% url 'accounts:mypage' profile.id %}">mypage</a></li> {% endcomment %}
        {% endif %}
    {% else %}
        <li><a href="{% url 'accounts:login' %}">login</a></li>
        <li><a href="{% url 'accounts:signup' %}">signup</a></li>
    {% endif %}
  </ul>
</div>

team6/cigarettes/templates/cigarettes/cigarette_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    h1 {
            margin-top: 30px;
            text-align: center;
            font-size: 1.75rem;
            font-family: 'Jua', sans-serif;
        }

    h3, p {
        font-family: 'Do Hyeon', sans-serif;
    }
    a .ciga {
        font-family: 'Do Hyeon', sans-serif;
        text-decoration: none !important;
        color : black;
    }

    .add_ciga {
        width: 100px;
        padding: .8em 0 10px .10em;
        background-color: #28A55F;
        border: none;
        color:  white;
        cursor: pointer;
        text-transform: uppercase;
        margin-top: 20px;
        text-align: center;
        font-family: 'Do Hyeon', sans-serif;
    }
</style>

<h1>Cigarette<br>
Detail page</h1>
<hr>
<h3>{{ tobacco.brand }} {{ tobacco.name }}</h3>
<br>
{% if tobacco.photo %}
    <div class="tobacco_photo">
        <img src="{{ tobacco.photo.url }}">
    </div>
{% endif %}
<p>
가격 : {{ tobacco.price }} <br>
출시일 : {{ tobacco.rel_date }} <br>
타격감 : {{ tobacco.feel_of_hit }} <br>
타르 함량 : {{ tobacco.TAR }} <br>
니코틴 함량 : {{ tobacco.nicotine }} <br>
별점 : {{ tobacco.score }} <br>
좋아요 수 : {{ tobacco.total_like }} <br>

{% if tobacco.c_type %}
    전자담배 종류 : {{ tobacco.c_type }} <br>
{% else %}
</p>
    {% if tobacco.is_local == True %} 국내판매 제품
    {% else %} 해외판매 제품
    {% endif %} <br>
    {% if tobacco.is_menthol == True %} 맨솔 유 {% else %} 맨솔 무 {% endif %} <br>
{% endif %}
<hr>
<h3> Comment </h3>
{% for comment in comment_list %}
    작성자 : {{ comment.belongs_to_user.nickname }}<br>
    타격감 : {{comment.feel_of_hit}}<br>
    별점 : {{comment.score}}<br>
    내용 : {{comment.content}}<br>
    <hr>
{% endfor %} 
<a class="add_ciga" href="{% url 'cigarettes:comment' tobacco.id %}">댓글작성</a>
<br><br>
<a href="{% url 'cigarettes:index' %}">Home</a>
<a href="{% url 'cigarettes:edit_cigarette' tobacco.id %}">Update</a>
{% endblock %}

team6/cigarettes/templates/cigarettes/cigarette_list.html
<h1>구름 쪼아</h1>

team6/cigarettes/templates/cigarettes/comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    h1 {
            margin-top: 30px;
            text-align: center;
            font-size: 1.75rem;
            font-family: 'Jua', sans-serif;
        }

    h3, p {
        font-family: 'Do Hyeon', sans-serif;
    }
    a .ciga {
        font-family: 'Do Hyeon', sans-serif;
        text-decoration: none !important;
        color : black;
    }

    .add_ciga {
        width: 100px;
        padding: .8em 0 10px .10em;
        background-color: #28A55F;
        border: none;
        color:  white;
        cursor: pointer;
        text-transform: uppercase;
        margin-top: 20px;
        text-align: center;
        font-family: 'Do Hyeon', sans-serif;
    }

    form {
        font-family: 'Do Hyeon', sans-serif;
        font-size: 0.8em;
    }
</style>
<h1>Create Comment<h1>
<hr>
<form action="{% url 'cigarettes:comment' cigarette_id%}" method="POST">
        {% csrf_token %}
    작성자 : {{profile.nickname}}<br>
    <hr>
    타격감 <br> 
    <input type="radio" name="feel_of_hit" value="상">상
    <input type="radio" name="feel_of_hit" value="중">중
    <input type="radio" name="feel_of_hit" value="하">하
    <br>
    별점<br>
    <input type="radio" name="score" value=1>1
    <input type="radio" name="score" value=2>2
    <input type="radio" name="score" value=3>3
    <input type="radio" name="score" value=4>4
    <input type="radio" name="score" value=5>5
    <br>
    내용 <br>
    <input type="text" name="content" value=""> 
    <br>
    <br>
    <input class="add_ciga" type="submit" value="댓글달기">
</form>
{% endblock %}

team6/cigarettes/templates/cigarettes/create_tobacco.html
{% extends 'base.html' %}

{% block content %}
<style>
    h1 {
        margin-top: 30px;
        text-align: center;
        font-size: 1.75rem;
        font-family: 'Jua', sans-serif;
    }
    
    p {
        font-family: 'Do Hyeon', sans-serif;
    }

    form {
    justify-content: center;
    font-family: 'Do Hyeon', sans-serif;
    }

    input[type="text"] {
    width: 100%;
    }

    .add_ciga {
    width: 100%;
    padding: .8em 0 10px .8em;
    background-color: #28A55F;
    border: none;
    color:  white;
    cursor: pointer;
    text-transform: uppercase;
    margin-top: 20px;
    }
    </style>

{% ifequal tobacco_type 'cigarette' %}
    {% ifequal mode 'create' %}


        <h1>Add Cigarette</h1>
        <form method="POST" action="{% url 'cigarettes:create_cigarette' %}">
            {% csrf_token %}
            <br>
            <input type="radio" name="is_local" value=True>국내판매 제품
            <input type="radio" name="is_local" value=False>해외판매 제품
            <br>
            브랜드 명: <input name="brand" type="text" value="">
            <br>
            제품 명: <input name="name" type="text" value="">
            <br>
            이미지: <input type="file" class="" accept=".jpg,.jpeg,.png,.gif" name="photo">
            <br>
            가격 : <input name="price" type="text" value="">
            <br>
            타르 함량 : <input name="tar" type="text" value="">
            <br>
            니코틴 함량 : <input name="nicotine" type="text" value="">
            <br>
            출시일 : <input name="rel_date" type="text" value="">
            <br>
            <input type="radio" name="is_menthol"  value=True>맨솔 유
            <input type="radio" name="is_menthol"  value=False>맨솔 무
            <br><br>
            <input class="add_ciga" type="submit" value="연초 추가">
            <br>
        </form>

    {% else %}
        <h1>Update Cigarette</h1>
        <form method="POST" action="{% url 'cigarettes:update_cigarette' edit_cigarette.id %}">
            {% csrf_token %}
            <br>
            <input type="radio" name="is_local" value=True>국내판매 제품
            <input type="radio" name="is_local" value=False>해외판매 제품
            <br>
            브랜드 명: <input name="brand" type="text" value={{edit_cigarette.brand}}>
            <br>
            제품 명: <input name="name" type="text" value={{edit_cigarette.name}}>
            <br>
            이미지: <input type="file" class="" accept=".jpg,.jpeg,.png,.gif" name="photo">
            <br>
            가격 : <input name="price" type="text" value={{edit_cigarette.price}}>
            <br>
            타르 함량 : <input name="tar" type="text" value={{edit_cigarette.TAR}}>
            <br>
            니코틴 함량 : <input name="nicotine" type="text" value={{edit_cigarette.nicotine}}>
            <br>
            출시일 : <input name="rel_date" type="text" value={{edit_cigarette.rel_date}}>
            <br>
            <input type="radio" name="is_menthol"  value=True>맨솔 유
            <input type="radio" name="is_menthol"  value=False>맨솔 무
            <br><br>
            <input class="add_ciga" type="submit" value="연초 추가">
            <br>
        </form>

    {% endifequal %}


{% else %}
    {% ifequal mode 'create' %}
        <h1>Add E-Cigarette</h1>
        <form method="POST" action="{% url 'cigarettes:create_elec_cigarette' %}">
            {% csrf_token %}
            <br>
            <input type="radio" name="c_type"  value="액상">액상형
            <input type="radio" name="c_type"  value="궐련">궐련형
            <input type="radio" name="c_type"  value="카트리지">카트리지형
            <br>
            브랜드 명: <input name="brand" type="text" value="">
            <br>
            제품 명: <input name="name" type="text" value="">
            <br>
            이미지: <input type="file" class="" accept=".jpg,.jpeg,.png,.gif" name="photo">
            <br>
            가격 : <input name="price" type="text" value="">
            <br>
            타르 함량 : <input name="tar" type="text" value="">
            <br>
            니코틴 함량 : <input name="nicotine" type="text" value="">
            <br>
            출시일 : <input name="rel_date" type="text" value="">
            <br><br>
            <input class="add_ciga" type="submit" value="전자담배 추가">
            <br>
        </form>
    {% else %}
        <h1>Update E-Cigarette</h1>
        <form method="POST" action="{% url 'cigarettes:update_elec_cigarette' edit_elec_cigarette.id %}">
            {% csrf_token %}
            <br>
            <input type="radio" name="c_type"  value="액상">액상형
            <input type="radio" name="c_type"  value="궐련">궐련형
            <input type="radio" name="c_type"  value="카트리지">카트리지형
            <br>
            브랜드 명: <input name="brand" type="text" value={{edit_elec_cigarette.brand}}>
            <br>
            제품 명: <input name="name" type="text" value={{edit_elec_cigarette.name}}>
            <br>
            이미지: <input type="file" class="" accept=".jpg,.jpeg,.png,.gif" name="photo">
            <br>
            가격 : <input name="price" type="text" value={{edit_elec_cigarette.price}}>
            <br>
            타르 함량 : <input name="tar" type="text" value={{edit_elec_cigarette.TAR}}>
            <br>
            니코틴 함량 : <input name="nicotine" type="text" value={{edit_elec_cigarette.nicotine}}>
            <br>
            출시일 : <input name="rel_date" type="text" value={{edit_elec_cigarette.rel_date}}>
            <br><br>
            <input class="add_ciga" type="submit" value="전자담배 추가">
            <br>
        </form>
    {% endifequal %}

{% endifequal %}

{% endblock %}

team6/cigarettes/templates/cigarettes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    h1 {
            margin-top: 30px;
            text-align: center;
            font-size: 1.75rem;
            font-family: 'Jua', sans-serif;
        }

    h3, p {
        font-family: 'Do Hyeon', sans-serif;
    }
    a .ciga {
        font-family: 'Do Hyeon', sans-serif;
        text-decoration: none !important;
        color : black;
    }
</style>
<h1>Cigarettes's Recommendation</h1>
<hr>
<img src="{% static 'img/ciga2.jpg' %}" width="100%" height="`00px" alt="cigarette">
<hr>
<h3>어떤 담배를 원하시나요?</h3>
  {% if user.is_authenticated %}
      <p>{{ user.username }}님 반갑습니다</p>
      <p>E-mail : {{ user.profile.email }}</p>
      <p>Nickname : {{ user.profile.nickname }}</p>
      {% if not user.is_superuser %}
        <a href="{% url 'accounts:mypage' profile.id  %}">MyPage</a>
      {% endif %}
      <a href="{% url 'cigarettes:new_cigarette' %}">연초 추가</a>
      <a href="{% url 'cigarettes:new_elec_cigarette' %}">전자담배 추가</a>
  {% else %}
      <a href="{% url 'accounts:signup'%}">Signup</a>
      <a href="{% url 'accounts:login'%}">Login</a>
  {% endif %}
  <hr>
  <h3>담배 목록 보기</h3>
  {% for toba in tobacco %}
   
  <img src="{% static 'img/ciga.jpg' %}" width="100px" height="100px" alt="cigarette">
    <a class="ciga" href="{% url 'cigarettes:detail' toba.id %}">
        
        {{toba.brand}} {{toba.name}}
        <br>
    </a>
    <hr>
    {% endfor %}
{% endblock %}